name: rtenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - curl=8.2.1
  - expat=2.5.0
  - gdbm=1.18
  - gettext=0.21.0
  - git=2.40.1
  - icu=73.1
  - intel-openmp=2023.1.0
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libcurl=8.2.1
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.52.0
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxml2=2.10.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numexpr=2.8.4
  - openssl=3.0.11
  - pcre2=10.42
  - perl=5.34.0
  - pip=23.2.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - appdirs==1.4.4
      - arch==6.2.0
      - beautifulsoup4==4.12.2
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - contourpy==1.1.1
      - cycler==0.12.0
      - datetime==5.2
      - fonttools==4.43.0
      - frozendict==2.3.8
      - html5lib==1.1
      - idna==3.4
      - inflection==0.5.1
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - llvmlite==0.41.0
      - lxml==4.9.3
      - matplotlib==3.8.0
      - more-itertools==10.1.0
      - multitasking==0.0.11
      - numba==0.58.0
      - numpy==1.25.2
      - packaging==23.1
      - pandas==2.1.1
      - pandas-datareader==0.10.0
      - patsy==0.5.3
      - peewee==3.16.3
      - pillow==10.0.1
      - plotly==5.17.0
      - plotly-express==0.4.1
      - pyarrow==13.0.0
      - pyparsing==3.1.1
      - quandl==3.7.0
      - requests==2.31.0
      - risktools==0.2.8.4
      - scikit-learn==1.3.1
      - scipy==1.11.3
      - seaborn==0.13.0
      - soupsieve==2.5
      - statsmodels==0.14.0
      - tenacity==8.2.3
      - threadpoolctl==3.2.0
      - urllib3==2.0.5
      - webencodings==0.5.1
      - yfinance==0.2.31
      - zope-interface==6.1
