name: rtenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aws-c-auth=0.7.7
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.8
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.14
  - aws-c-io=0.13.35
  - aws-c-mqtt=0.9.9
  - aws-c-s3=0.3.24
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.24.7
  - aws-sdk-cpp=1.11.182
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.22.1
  - ca-certificates=2023.11.17
  - certifi=2023.11.17
  - charset-normalizer=3.3.2
  - curl=8.4.0
  - gettext=0.21.1
  - gflags=2.2.2
  - git=2.42.0
  - glog=0.6.0
  - icu=73.2
  - idna=3.4
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - libabseil=20230802.1
  - libarrow=14.0.1
  - libarrow-acero=14.0.1
  - libarrow-dataset=14.0.1
  - libarrow-flight=14.0.1
  - libarrow-flight-sql=14.0.1
  - libarrow-gandiva=14.0.1
  - libarrow-substrait=14.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.4.0
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libnuma=2.0.16
  - libopenblas=0.3.24
  - libparquet=14.0.1
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - libsqlite=3.44.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libxml2=2.11.6
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lxml=4.9.3
  - lz4-c=1.9.4
  - ncurses=6.4
  - numpy=1.26.0
  - openssl=3.1.4
  - orc=1.9.0
  - packaging=23.2
  - pandas=2.1.3
  - pandas-datareader=0.10.0
  - pcre2=10.40
  - perl=5.32.1
  - pip=23.3.1
  - plotly=5.18.0
  - pyarrow=14.0.1
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - rdma-core=28.9
  - re2=2023.06.02
  - readline=8.2
  - requests=2.31.0
  - s2n=1.3.56
  - scipy=1.11.3
  - setuptools=68.2.2
  - six=1.16.0
  - snappy=1.1.10
  - tenacity=8.2.3
  - tk=8.6.13
  - tzdata=2023c
  - ucx=1.15.0
  - urllib3=2.1.0
  - wheel=0.41.3
  - xz=5.2.6
  - zstd=1.5.5
  - pip:
      - arch==6.2.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - fonttools==4.44.3
      - inflection==0.5.1
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.8.2
      - more-itertools==10.1.0
      - patsy==0.5.3
      - pillow==10.1.0
      - pyparsing==3.1.1
      - quandl==3.7.0
      - risktools==0.2.8.4
      - scikit-learn==1.3.2
      - seaborn==0.13.0
      - statsmodels==0.14.0
      - threadpoolctl==3.2.0
