name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Updated to the latest version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build and push Docker image (with python and node)
        uses: docker/build-push-action@v5
        with:
          context: ./rstudio-python-node
          file: ./rstudio-python-node/Dockerfile
          push: true
          tags: risktoollib/rstudio-python-node:latest

      - name: Build and push Docker image (with python uv and node)
        uses: docker/build-push-action@v5
        with:
          context: ./rstudio-python-node
          file: ./rpn/Dockerfile
          push: true
          tags: risktoollib/rpn:latest