name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker image 1
      uses: docker/build-push-action@v2
      with:
        context: ./rstudio-pyconda
        file: ./rstudio-pyconda/Dockerfile
        push: true
        tags: risktoollib/rstudio-pyconda:latest

    - name: Build and Push Docker image 2
      uses: docker/build-push-action@v2
      with:
        context: ./rstudio-pyconda-node
        file: ./rstudio-pyconda-node/Dockerfile
        push: true
        tags: risktoollib/rstudio-pyconda-node:latest
